- name: "Copy configuration files for Kea DHCP{{ outer_item.dhcp_ip_version }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ kea_container_base_dir }}/config/{{ item | regex_replace('.j2', '') }}"
    owner: 'root'
    group: '101'
    mode: '0664'
  loop:
    - "dhcp{{ outer_item.dhcp_ip_version }}.json.j2"
    - "subnet{{ outer_item.dhcp_ip_version }}.json.j2"
  register: kea_config

- name: "Start container for Kea DHCP{{ outer_item.dhcp_ip_version }}"
  community.docker.docker_container:
    name: "{{ outer_item.container_name }}"
    image: "{{ outer_item.container_image }}"
    pull: true
    state: started
    restart_policy: unless-stopped
    command: "{{ outer_item.container_command }}"
    volumes:
      - "{{ kea_container_base_dir }}/config:/kea/config:ro"
      - "{{ kea_container_base_dir }}/leases:/kea/leases"
      - "{{ kea_container_base_dir }}/logs:/kea/logs"
      - "{{ kea_container_base_dir }}/sockets:/kea/sockets"
      - "{{ kea_container_base_dir }}/entrypoint.d:/entrypoint.d:ro"
    network_mode: host
    purge_networks: true

- name: "Reload configuration for Kea DHCP{{ outer_item.dhcp_ip_version }}"
  when: kea_config.changed # noqa: no-handler
  ansible.builtin.command: "docker kill --signal=HUP {{ outer_item.container_name }}"
  register: docker_output # noqa: key-order[task]
  changed_when: docker_output.rc == 0
  notify: Reload Kea Control Agent
