---
# tasks file for cluster-setup

- name: Setup host file
  ansible.builtin.blockinfile:
    path: /etc/hosts
    append_newline: true
    prepend_newline: true
    block: |
      {{ main_node_ip }} main-node
      {{ node_1_ip }} node-1
      {{ node_2_ip }} node-2
      {{ node_3_ip }} node-3

- name: Cluster Token
  ansible.builtin.debug:
    msg: "{{ cluster_token }}"

- name: Setup keyring folder
  ansible.builtin.file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: "0755"
    state: "directory"

- name: Pull kubernetes release key
  ansible.builtin.uri:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/release.key
    follow_redirects: "all"
    status_code: [200, 304]
    method: "GET"
    mode: "a+r"

- name: Get data on GPG file
  ansible.builtin.stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: gpg_file

- name: Add kubernetes key to gpg
  ansible.builtin.command:
    cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/release.key"
  when: not gpg_file.stat.exists

- name: Create apt kubernetes file
  ansible.builtin.template:
    src: templates/kubernetes.list.j2
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: "0644"

- name: Apt Update
  ansible.builtin.apt:
    update_cache: true

- name: Install kubernetes dependencies
  ansible.builtin.package:
    name:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
    state: present

- name: Setup main node
  ansible.builtin.include_tasks:
    file: main-node.yml
  when: inventory_hostname == "main-node"

- name: Setup nodes
  ansible.builtin.include_tasks:
    file: nodes.yml
  when: inventory_hostname != "main-node"
