---
- name: Create swap folder for kubernetes
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    mode: go=

- name: Create swap file
  ansible.builtin.copy:
    src: files/20-allow-swap.conf
    dest: /etc/systemd/system/kubelet.service.d/20-allow-swap.conf
    mode: go=

- name: Restart daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Reset kubeadm
  ansible.builtin.command:
    cmd: kubeadm reset -f
  changed_when: true

- name: Setup cluster
  ansible.builtin.command:
    cmd: >
      kubeadm init --pod-network-cidr {{ cluster_setup_pod_cidr }}
      --token {{ cluster_token }}
      --apiserver-advertise-address {{ cluster_setup_main_node_ip }}
      --apiserver-cert-extra-sans kubernetes.cluster.home
      --ignore-preflight-errors=Mem,Swap
  changed_when: true
