---
- name: Reset kubeadm
  ansible.builtin.command:
    cmd: kubeadm reset -f
  changed_when: true

- name: Join cluster
  ansible.builtin.command:
    cmd: >
      kubeadm join
      --config /etc/kubernetes/cluster-config.yml
  changed_when: true
