---
- name: Reset kubeadm
  ansible.builtin.command:
    cmd: kubeadm reset -f
  changed_when: true

- name: Join cluster
  ansible.builtin.command:
    cmd: >
      kubeadm join {{ cluster_setup_main_node_ip }}:6443
      --discovery-token-unsafe-skip-ca-verification
      --token={{ cluster_token }}
  changed_when: true
