---
- name: Install WireGuard
  ansible.builtin.package:
    name:
      - wireguard
    state: present

- name: Generate private key
  ansible.builtin.command:
    cmd: wg genkey
  changed_when: true
  register: wg_private_key

- name: Debug private key
  ansible.builtin.debug:
    msg: "{{ wg_private_key }}"

- name: Write private key
  ansible.builtin.copy:
    content: "{{ wg_private_key.stdout }}"
    dest: /etc/wireguard/private.key
    force: true
    mode: go=

- name: Generate public key
  ansible.builtin.command:
    cmd: wg pubkey
    stdin: "{{ wg_private_key.stdout }}"
  changed_when: true
  register: wg_public_key

- name: Debug public key
  ansible.builtin.debug:
    msg: "{{ wg_public_key }}"

- name: Write public key
  ansible.builtin.copy:
    content: "{{ wg_public_key.stdout }}"
    dest: /etc/wireguard/public.key
    force: true
    mode: go=

- name: Create peer private key
  ansible.builtin.command:
    cmd: wg genkey
  changed_when: true
  register: wg_peer_private_key

- name: Create peer public key
  ansible.builtin.command:
    cmd: wg pubkey
    stdin: "{{ wg_peer_private_key.stdout }}"
  changed_when: true
  register: wg_peer_public_key

- name: "Check {{ tunnel_interface }} interface status"
  ansible.builtin.command:
    cmd: "wg showconf {{ tunnel_interface }}"
  changed_when: true
  ignore_errors: true
  register: tunnel_status

- name: "Shutdown interface to update server {{ tunnel_interface }} config"
  ansible.builtin.command:
    cmd: "wg-quick down {{ tunnel_interface }}"
  when: tunnel_status.rc == 0

- name: Setup {{ tunnel_interface }} config
  ansible.builtin.template:
    src: "templates/conf.j2"
    dest: /etc/wireguard/{{ tunnel_interface }}.conf
    mode: go=

- name: Writing peer config to local file
  ansible.builtin.template:
    src: "templates/peer.conf.j2"
    dest: "{{ tunnel_interface }}.peer.conf"
  delegate_to: localhost

- name: Enable and bounce WireGuard Service
  ansible.builtin.service:
    name: wg-quick@{{ tunnel_interface }}.service
    state: restarted
    enabled: true

- name: "Setup {{ tunnel_interface }} peer"
  ansible.builtin.command:
    cmd: "wg set {{ tunnel_interface }} peer {{ wg_peer_public_key.stdout }} allowed-ips {{ allowed_ips }}"
  changed_when: true
