---
# tasks file for pivpn
- name: Setup pivpn folder
  file:
    path: "{{ pivpn_dir }}"
    state: directory
    mode: 0744
    owner: pi
    group: pi

- name: Grab pivpn config file
  ansible.builtin.get_url:
    url: "{{ pivpn_url }}"
    dest: "{{ pivpn_dir }}"
    mode: 0744

- name: Copy over config file
  ansible.builtin.copy:
    src: ./playbooks/roles/pivpn/templates/setup.conf.j2
    dest: "{{ pivpn_dir }}/setup.conf"

- name: Run the pivpn setup script
  ansible.builtin.script:
    cmd: "{{ pivpn_dir }}/setup.conf -s --unattended {{ pivpn_dir }}/setupVars.conf"
