---
# tasks file for pivpn
- name: Setup pivpn folder
  ansible.builtin.file:
    path: "{{ pivpn_dir }}"
    state: directory
    mode: "0744"
    owner: pi
    group: pi
  become: true

- name: Grab pivpn config file
  ansible.builtin.get_url:
    url: "{{ pivpn_url }}"
    dest: "{{ pivpn_dir }}"
    mode: "0744"
  become: true

- name: Copy over config file
  ansible.builtin.template:
    src: templates/setup.conf.j2
    dest: "{{ pivpn_dir }}/setup.conf"
    mode: "0744"
  become: true

- name: Run the pivpn setup script
  ansible.builtin.command:
    cmd: "{{ pivpn_dir }}/install.sh -s --unattended {{ pivpn_dir }}/setup.conf"
    creates: "{{ pivpn_dir }}/openvpn"
  become: true

- name: Create ovpn file
  ansible.builtin.command:
    cmd: pivpn add --name main-node --password {{ pivpn_password }} --days 365
    creates: /home/pi/ovpns/main-node.ovpn
  no_log: true

- name: Fetch ovpn file
  ansible.builtin.fetch:
    src: /home/pi/ovpns/main-node.ovpn
    dest: main-node.ovpn
