---
# tasks file for networking

# Turn on IP Forwarding
- name: Setup IP Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: true

# Use dhcpcd.conf to set static IP
- name: Apply dhcpcd.conf file
  ansible.builtin.template:
    src: templates/dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    mode: "0744"
  become: true

# Reboot the node, kernel updates require a reboot for iptables to work
- name: Reboot Pi
  ansible.builtin.reboot:
  become: true

# Update IPTABLE Rules
- name: IPTABLES - WLAN0 MASQUERADE
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: wlan0
    jump: MASQUERADE
  become: true

- name: IPTABLES - FORWARD WLAN0 to ETH0
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: wlan0
    out_interface: eth0
    match: state
    ctstate: RELATED,ESTABLISHED
    jump: ACCEPT
  become: true

- name: IPTABLES - FORWARD ETH0 to WLAN0
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: eth0
    out_interface: wlan0
    jump: ACCEPT
  become: true
