---
# tasks file for networking

# Turn on IP Forwarding for masquerading
- name: Setup IP Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: true

# Use dhcpcd.conf to ignore ETH0, this will enable kea-dhcp4 to work
- name: Apply dhcpcd.conf file
  ansible.builtin.blockinfile:
    path: /etc/dhcpcd.conf
    append_newline: true
    prepend_newline: true
    insertafter: "EOF"
    block: |
      denyinterface eth0
  become: true

- name: Setup static network on eth0
  ansible.builtin.template:
    src: eth0.j2
    dest: /etc/network/interfaces.d/eth0
    owner: root
    group: root
    mode: '0644'
  become: true

# NFTable setup
- name: Overwrite nftables.conf
  ansible.builtin.copy:
    src: files/nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Enable and restart NFTables
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: restarted

# Reboot the node, kernel updates require a reboot for iptables to work
- name: Reboot Pi
  ansible.builtin.reboot:
  become: true
