---
- name: Setup the kubernetes cluster

  hosts: all
  become: true

  tasks:
    - name: Read in inventory file
      ansible.builtin.include_vars:
        file: "{{ ansible_inventory_sources[0] }}"
        name: inventory_file

    - name: Generate k8s token components # noqa: run-once[task]
      ansible.builtin.set_fact:
        token_first_half: "{{ lookup('community.general.random_string', special=false, upper=false, length=6) }}"
        token_second_half: "{{ lookup('community.general.random_string', special=false, upper=false, length=16) }}"
      run_once: true

    - name: Generate k8s setup token # noqa: run-once[task]
      ansible.builtin.set_fact:
        cluster_token: "{{ token_first_half }}.{{ token_second_half }}"
      run_once: true

    - name: Setup docker
      ansible.builtin.include_role:
        name: docker

    - name: Setup cluster
      ansible.builtin.include_role:
        name: cluster_setup
      vars:
        cluster_setup_pod_cidr: "10.244.0.0/16"
        cluster_setup_main_node_ip: "{{ inventory_file.cluster.hosts['main-node'].ip_address }}"
        cluster_setup_node_1_ip: "{{ inventory_file.cluster.hosts['node-1'].ip_address }}"
        cluster_setup_node_2_ip: "{{ inventory_file.cluster.hosts['node-2'].ip_address }}"
        cluster_setup_node_3_ip: "{{ inventory_file.cluster.hosts['node-3'].ip_address }}"
        k8s_version: "{{ inventory_file.k8s_version }}"
