---
# This is the first round of main-node setup

- name: Setup main-node networking
  hosts: main-node
  tasks:
    - name: Debug vars
      ansible.builtin.debug:
        var: ansible_inventory_sources
    - name: Read in inventory file
      ansible.builtin.include_vars:
        file: "{{ ansible_inventory_sources[0] }}"
        name: inventory_file
    - name: Print out file
      ansible.builtin.debug:
        var: inventory_file
    - name: Access Test ======================
      ansible.builtin.debug:
        msg: "{{ inventory_file.cluster.hosts['main-node'].ip_address }}"

    - name: Run networking role
      ansible.builtin.include_role:
        name: networking
      vars:
        networking_ip_address: "{{ inventory_file.cluster.hosts['main-node'].ip_address }}"

    # - name: Run dnsmasq role
    #  ansible.builtin.include_role:
    #    name: dnsmasq

    # - name: Run pivpn role
    #  ansible.builtin.include_role:
    #    name: pivpn
