---
# This is the first round of main-node setup

- name: Setup main-node networking
  hosts: main-node

  # vars_prompt:
  #   - name: ovpn_password
  #     prompt: Enter ovpn file password

  tasks:
    - name: Read in inventory file
      ansible.builtin.include_vars:
        file: "{{ ansible_inventory_sources[0] }}"
        name: inventory_file

    - name: Run networking role
      ansible.builtin.include_role:
        name: networking
      vars:
        networking_ip_address: "{{ inventory_file.cluster.hosts['main-node'].ip_address }}"
    
    - name: Setup kea-dhcp4
      ansible.builtin.include_role:
        name: kea
      vars:
        kea_dhcp_interfaces: [ 'eth0' ]
        kea_dhcp4_subnets:
          subnet: "10.0.0.0/24"
          pools:
            - pool: "10.0.0.2 - 10.0.0.20"
          option-data:
            - routers: "{{ inventory_file.cluster.hosts['main-node'].ip_address }}"
            - domain-name-servers: "1.1.1.1, 9.9.9.9"
            - domain-name: "cluster.home"

    # - name: Run dnsmasq role
    #   ansible.builtin.include_role:
    #     name: dnsmasq

    # - name: Run pivpn role
    #   ansible.builtin.include_role:
    #     name: pivpn
    #   vars:
    #     pivpn_password: "{{ ovpn_password }}"
