---
# This is the first round of main-node setup

- name: Setup main-node networking
  hosts: main-node

  vars_prompt:
    - name: ovpn_password
      prompt: Enter ovpn file password

  tasks:
    - name: Read in inventory file
      ansible.builtin.include_vars:
        file: "{{ ansible_inventory_sources[0] }}"
        name: inventory_file

    - name: Run networking role
      ansible.builtin.include_role:
        name: networking
      vars:
        networking_ip_address: "{{ inventory_file.cluster.hosts['main-node'].ip_address }}"

    - name: Run dnsmasq role
      ansible.builtin.include_role:
        name: dnsmasq

    - name: Run pivpn role
      ansible.builtin.include_role:
        name: pivpn
      vars:
        pivpn_password: "{{ ovpn_password }}"
