---
- name: Setup the kubernetes cluster

  hosts: all
  become: true

  tasks:
    - name: Read in inventory file
      ansible.builtin.include_vars:
        file: "{{ ansible_inventory_sources[0] }}"
        name: inventory_file

    - name: Generate k8s setup token
      ansible.builtin.set_fact:
        cluster_token: "{{ lookup('community.general.random_string', special=false, upper=false, length=6) }}.{{ lookup('community.general.random_string', special=false, upper=false, length=16) }}"
      run_once: true

    - name: Token value
      ansible.builtin.debug:
        msg: "{{ cluster_token }}"

    - name: Test vars
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"

    - name: Setup cluster
      ansible.builtin.include_role:
        name: cluster_setup
      vars:
        cluster_setup_pod_cidr: "10.244.0.0/16"
        main_node_ip: "{{ inventory_file.cluster.hosts['main-node'].ip_address }}"
        node_1_ip: "{{ inventory_file.cluster.hosts['node-1'].ip_address }}"
        node_2_ip: "{{ inventory_file.cluster.hosts['node-2'].ip_address }}"
        node_3_ip: "{{ inventory_file.cluster.hosts['node-3'].ip_address }}"
