name: Ansible Lint
# Base work pulled from: https://github.com/ansible/ansible-lint-action
# Need to disable truthy check for `on` key
on: [push, pull_request] # yamllint disable-line rule:truthy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Install pip requirements
        run: pip install -r requirements.txt

      - name: Ansible version
        run: ansible --version

      - name: Ansible collections installed
        run: ansible-galaxy collection list

      - name: Ansible Linter
        uses: ansible/ansible-lint-action@main
        env:
          ANSIBLE_LIBRARY: '/usr/share/ansible/collections'
        with:
          path: /home/runner/.local/lib/python3.10/site-packages/ansible_collections
