name: Ansible Lint
# Base work pulled from: https://github.com/ansible/ansible-lint-action
# Need to disable truthy check for `on` key
on: [push, pull_request] # yamllint disable-line rule:truthy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Setup and run linter
        run: |
          ${PWD}/setup_venv.sh
          source ${PWD}/venv/bin/activate
          ansible-lint
